### ISSUE TITLE
[Question] Nested stacks

### ISSUE THREAD

**Issue by RayZik** [neilkuan/cdk-aurora-globaldatabase#1549]
Hi! 
Does it work via a Nested Stack? 

I have some problems with Nested Stacks. When I try to do
```
      this.primaryDbStack = new cdk.**NestedStack**(
        this,
        formatResourceId('AuroraPrimary'),
      );
      
      this.globalPrimaryDb = new GlobalAuroraRDSMaster(
        this.primaryDbStack,
        'GarM',
        {
          ...
          credentials,
          vpc: this.vpcStack.vpc,
          ...
        }
      );
```

It just fails...

<img width="1697" alt="Screenshot 2023-09-12 at 07 38 38" src="https://github.com/neilkuan/cdk-aurora-globaldatabase/assets/22475031/f2694a33-71a9-4aee-a1ce-4e53a4112b4e">

![Screenshot 2023-09-12 at 07 43 45](https://github.com/neilkuan/cdk-aurora-globaldatabase/assets/22475031/4a3ac7b8-8192-49c3-8a31-fa7d85a10cd9)

It sounds like it doesn't work via Nested. Maybe cuz this -> https://github.com/neilkuan/cdk-aurora-globaldatabase/blob/master/src/index.ts#L619

Do you have any ideas? Thanks!

**Comment by RayZik** [comment]
@neilkuan Any ideas? :)

**Comment by neilkuan** [comment]
Can you give me more detail log about lambda handler log ?!

**Comment by RayZik** [comment]
I've just found the problem.
It happens cuz when we are using Nested stacks `stackName` is a token

https://github.com/neilkuan/cdk-aurora-globaldatabase/blob/master/src/index.ts#L668

We have to add some checks like 

```
if(cdk.Token.isUnresolved(stack.stackName)) {
  throw Error or allow users to provide their own prefix
}
```

> Can you give me more detail log about lambda handler log ?!
How can I do this?

**Comment by RayZik** [comment]
For testing I've tried to do smth like this
```
  const stackName = cdk.Token.isUnresolved(stack.stackName) ? stack.node.scope._stackName : stack.stackName;
 ```
 
 Deploying...

**Comment by RayZik** [comment]
The main problem is stackName used for instanceID

**Comment by neilkuan** [comment]
> The main problem is stackName used for instanceID

yes, maybe root case is here.

https://github.com/neilkuan/cdk-aurora-globaldatabase/blob/fbd39b056a756750c6ebe537dcd34d48ae86ab84/src/index.ts#L790

**Comment by RayZik** [comment]
@crisboarna Yep, confirmed! stack.stackName is equal to `${Token[TOKEN.934]}`

**Comment by RayZik** [comment]
@crisboarna I will do PR today :)
