### ISSUE TITLE
native cloudformation resource support

### ISSUE THREAD

**Issue by pahud** [neilkuan/cdk-aurora-globaldatabase#43]
FYI

New resource - The following resource was added: AWS::RDS::GlobalCluster. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-globalcluster.html

**Comment by snese** [comment]
@guan840912 I think this is good oppty. to contribute the official CDK L2 lib to the community.

Thought?

**Comment by guan840912** [comment]
give me some time XD

**Comment by pahud** [comment]
do not close :-)
