### ISSUE TITLE
Sample for Postgresql with CDK 2.45.0

### ISSUE THREAD

**Issue by cmorgia** [neilkuan/cdk-aurora-globaldatabase#887]
Hi Neil,
we've been in touch before regarding a PR :-)
I'm writing back to you since I was trying to use your repo with CDK 2.45.0 and I'm having an issue with the sample (and my code as well).
When the sample code tries to add the regional cluster, here's the error:
`Received response status [FAILED] from custom resource. Message returned: Error: 'securityGroup' Logs: /aws/lambda/testing-stackM-addregionalrdsaddRegionalonEvent84C-qZIHxmkVK9GF at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:365) at async Runtime.handler (/var/task/cfn-response.js:1:1474) (RequestId: 0fc35a0e-92bd-4ca3-93b4-d3cb8cdc7ddb)`

In my own code, I already add a security group and a parameter group but no matter what I do, I get an error like:
`Received response status [FAILED] from custom resource. Message returned: Error: 'dbParameterGroup' Logs: /aws/lambda/devPrimary-devPrimaryStac-auroraRegionaladdRegiona-sXXXB8KcUBjg at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:365) at async Runtime.handler (/var/task/cfn-response.js:1:1474) (RequestId: 13b62aea-9cf7-4dd1-bc7b-847cdfdf977f)`

Did it already happened to you? Any clue?

Thanks!
Claudio

**Comment by neilkuan** [comment]
Hello @cmorgia, thanks for report issue.
I will take a look this issue at this weekend. :)

**Comment by neilkuan** [comment]
okay 
I think issue is about this PR.
https://github.com/neilkuan/cdk-aurora-globaldatabase/pull/746/files

This pr make `dbParameterGroup` and `securityGroupId` optional.
But did not  check they is undefined in `add_region_index.py` to create rds cluster.

**Comment by neilkuan** [comment]
hi @cmorgia , I already create this PR #904 to fix this issue, let me know did this fix this issue?1
